In [1]:
import numpy as np   
scores = np.array([[85, 90, 78, 92, 88],
                   [72, 75, 80, 68, 74],
                   [95, 88, 92, 96, 90],
                   [60, 65, 70, 58, 62],
                   [88, 84, 86, 89, 87]])     

In [2]:
scores[2]

array([95, 88, 92, 96, 90])

In [3]:
scores[:,1]

array([90, 75, 88, 65, 84])

In [4]:
scores[:3,:2]

array([[85, 90],
       [72, 75],
       [95, 88]])

In [5]:
scores[2:,3:]

array([[96, 90],
       [58, 62],
       [89, 87]])

In [6]:
scores + 5

array([[ 90,  95,  83,  97,  93],
       [ 77,  80,  85,  73,  79],
       [100,  93,  97, 101,  95],
       [ 65,  70,  75,  63,  67],
       [ 93,  89,  91,  94,  92]])

In [7]:
scores[:,3] - 10

array([82, 58, 86, 48, 79])

In [8]:
scores.sum(axis=1) / 5

array([86.6, 73.8, 92.2, 63. , 86.8])

In [9]:
scores.mean(axis=1)

array([86.6, 73.8, 92.2, 63. , 86.8])

In [10]:
scores.sum(axis=1)

array([433, 369, 461, 315, 434])

In [11]:
np.max(scores)

96

In [12]:
scores.mean(axis=0)

array([80. , 80.4, 81.2, 80.6, 80.2])

In [13]:
np.argmin(average_scores)

NameError: name 'average_scores' is not defined

In [14]:
np.argmin(scores)

18